### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by jnz** [SirJson/rq3vm#1]
Now this is the first time for me to work with Rust and cargo. So this issue is either a README problem (to give the beginner some clear commands to type in) or there is actually a problem.

So I tried to run  `cargo run` in the example/helloq3 folder:

```
error[E0580]: main function has wrong type
  --> src/main.rs:19:1
   |
19 | fn main() -> Result<(), io::Error> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
   |
   = note: expected type `fn()`
              found type `fn() -> std::result::Result<(), std::io::Error>`

error: aborting due to 2 previous errors

error: Could not compile `helloq3`.
```

Before that I tried to run `cargo build` in the root directory.

**Comment by SirJson** [comment]
Sounds like an old Rust compiler. In order for main() to return the Result type you would need Rust >=1.26.0. If you installed Rust with rustup in the past that should be fixed with a simple `rustup update`

**Comment by jnz** [comment]
I've got Rust 1.25.0 from Ubuntu 17.10, so that explains it.

**Comment by SirJson** [comment]
In that case I highly recommend to rebel against your OS vendor and use rustup. It will install locally for your user so there shouldn't be any package manager problems, the whole process is almost fully automated, you can get additional tools via rustup and  the 2018 version of Rust is already in Beta which brings a lot of productivity improvements. 

This crate will always follow stable rust and I think I will make the upgrade to 2018 as soon as it is ready since it improves things like code readability a lot.
