### ISSUE TITLE
Functions StringNew and StringFree in helloq3 example project

### ISSUE THREAD

**Issue by jnz** [SirJson/rq3vm#2]
I am not sure if those functions would work. Now at the moment they are not implemented, but I assume that there will be some dynamic memory allocation involved. As the VM can only work with the data section (memory sandbox), an outside host address would not work. So the malloc function needs to be implemented in the VM itself (there is a implementation for Quake 3 that does that: https://icculus.org/homepages/phaethon/q3/malloc/malloc.html). Or the host manages part of the memory sandbox from the outside. And supplies the VM with valid virtual addresses for the malloc calls.

**Comment by SirJson** [comment]
They used to have a half baked implementation where I wanted q3vm to have a view to a Rust string. So all strings are owned by Rust and would have had the comfort of Rust. But then I remembered it probably wouldn't be a good idea to give someone a ptr directly to the Rust host.

For now they are stubbed with unimplemented!() because I got bureaucracy fatigue from reorganizing the project and following all rules in to get this crate published. The plan is now to implement fairly straight forward c-like strings but provided and checked by the host. If I remember correctly you made a handy function that provides some memory safety so they can't escape the VM.

The next step would be writing the adapter between Rust strings and q3vm strings. I think that shouldn't take too much time.

**Comment by jnz** [comment]
The thing is that you can't give the VM a pointer to the Rust host memory.
All VM memory access is limited to the sandbox memory array:

    vm->dataBase[]

So an address for the VM is an offset into that array. And each access is protected by a mask:

    vm->dataBase[addr & dataMask]

What you can do from the host side is to read and write data to that area to communicate with the VM.

**Comment by SirJson** [comment]
Yep that's what I thought. That's fortunately no problem since I can call almost everything from the C standard library in a special unsafe zone in Rust. So the implementation would be like in C but I can provide maybe additional checks or error messages.

The long term goal for me is to provide a cosy C environment together with an easy to use LÖVE-like function set to get beginners some way to get their feet wet before I hit them with reality. https://gitlab.com/SirJson/vaporkit

That function set will be somewhat inspired by DarkGDK / DarkBasic because that is what helped me back when it was released for free to get over my fear for C/C++. This is also the reason why I'm so interested in a q3vm compiler that implements c99 or even better c11 because that style is more like what people will find when they put down the training wheels. 

But so far I have the feeling everything is tightly designed around LCC so the best way would be to extend the compiler... maybe. Or they just have to code like it's 1989 ;-)

**Comment by jnz** [comment]
I am a big fan of C99 myself. So coding with C89 is something I don't really like, but I can tolerate it and changing LCC to support C99 is not a viable option. There is a LCC fork called lcc-win32 that has C99 support, but I am not sure if it is open-source software. I it is available somewhere and it can still emit the LCC bytecode, we could get C99 quite cheap.

**Comment by SirJson** [comment]
Hm I remember reading about lcc-win32. I followed the trail to a very small german company in the middle of nowhere that seems to be either defunct or barely staffed. It seems like they gave the project to the computer science department at the University of Virginia. 

There I also first found just broken links but with the magic of the _**Internet Wayback Machine**_ I was able to restore what used to be the lcc-win32 and lcc-win64 project. [Click here to go back in time](https://web.archive.org/web/20170321075240/http://www.cs.virginia.edu/~lcc-win32/) :sparkle:

Unfortunately it looks like they or he is using the same licence like the original lcc did. I was hoping since they are a University they would put it under a more liberal licence but it seems like the maintainer wanted to see some money if you use it for non-commercial purposes. Ok nothing lost nothing gained.

I assume the maintainer was a guy called "Jacob Navia". If you look closely you will see that some kind of project or library was also part of lcc-win32: CCL. And it looks like that project was important enough for him to save (if this is really his profile): https://github.com/jacob-navia

Since there is no way to buy the compiler now and if it works for us maybe we can ask him nicely if he donates it to the project. After all he isn't making money with it anymore and the downloads are officially dead.

But first things first I think I will infect my Windows PC with those binaries I just found. Let's see what happens...

(Also is there a way to fork discussions in Github like in a forum? We went kinda off topic :sweat_smile: )

**Comment by HarryR** [comment]
So, the following comment is highly disrespectful, and [Trigger Warning] if you are an intellectual property lawyer or otherwise deeply vested in the most recent form of cognitive slavery, then I suggest you look away now and ... I don't know, go and passively aggressively add some more restrictive terms to whatever contract you're currently drafting.

This is bullshit.

lcc is free, it should be free, it has always been 'free', it always will be free.

But the only thing getting in the way is the autist trap of a license agreement, which pulls us all into another domain to argue about semantics which don't matter.

</rant>

Begin software anarchy **now**, modify lcc and laugh at the license agreements. Relicense it as AGPLv3 and watch butthurt wannabe armchair-laywers writhe etc.

👍 

And if you find a bug, fax their lawyers a patch!

What matters more is, of all the people working on LCC, I think the license agreement has massively hindered our ability to collectively co-operate. Github is the time and the place, and our shared needs and effort are continuously being slammed down by our own self-censorship over the 'license agreement'.

Guess what, I never read it. Somebody send me a copy of the source without the license, and I'll re-host it and give all necessary people admin access to the repo so they can *get shit done* in a way which helps everybody.

**Comment by SirJson** [comment]
Ok that was a little extreme, but I agree that it was a bit ridiculous in the first place to sell that compiler if you have universities like the University of Illinois who create better software and release that with a free licence. Also that lcc was a product of shared knowledge nothing revolutionary.

In the end getting mad over lcc is stupid anyways because it is really not that great of a compiler. It was maybe a good option in '99 but we can do better.

I close that issue now since we should discuss this not here and all answers to string allocation are answered :wink:
